// Grandfathered size-ratchet offenders (eslint.size.config.js).
//
// Generated from files that violate max-lines (300, all files) or
// max-lines-per-function (50, non-test files only -- test files are
// exempt from that rule in eslint.size.config.js, since ESLint counts a
// describe(...) callback's body as one function, and grouping related
// test cases under a describe routinely exceeds 50 lines regardless of
// file size). Paths are relative to src/quodeq/ui, posix-separated. The
// list may only shrink: split a file, then remove its entry here
// (tools/check_size_grandfather.mjs enforces the ceiling).
export const SIZE_GRANDFATHER = [
  "src/App.jsx",
  "src/api/applyMutationDelta.js",
  "src/components/ContextBlock.jsx",
  "src/components/HeatGridCells.jsx",
  "src/components/Sidebar.jsx",
  "src/components/TopBar.jsx",
  "src/components/terminal/SevBadge.jsx",
  "src/features/assistant/AssistantDrawerProvider.jsx",
  "src/features/assistant/AssistantHeader.jsx",
  "src/features/assistant/hooks/useSessionLifecycle.js",
  "src/features/assistant/useAssistantStream.js",
  "src/features/assistant/useDrawerPanels.js",
  "src/features/dashboard/components/AccumulatedOverviewPanel.jsx",
  "src/features/dashboard/components/DashboardPage.jsx",
  "src/features/dashboard/components/DimensionGaugeCard.jsx",
  "src/features/dashboard/components/RunNavigator.jsx",
  "src/features/dashboard/hooks/useDashboard.js",
  "src/features/dashboard/hooks/useSharedProjects.js",
  "src/features/drawer/BottomDrawer.jsx",
  "src/features/evaluation/components/BranchScopeSelector.jsx",
  "src/features/evaluation/components/CleanScanToggle.jsx",
  "src/features/evaluation/components/ConsoleLogViewer.jsx",
  "src/features/evaluation/components/FolderBrowser.jsx",
  "src/features/evaluation/components/JobStatStrip.jsx",
  "src/features/evaluation/components/scanProgressTotals.js",
  "src/features/evaluation/eval-log/EvalLogProvider.jsx",
  "src/features/evaluation/eval-log/useJobLogStream.js",
  "src/features/evaluation/hooks/useRunEventStream.js",
  "src/features/explorer/components/DimensionScoreHistoryPanel.jsx",
  "src/features/explorer/components/FilePickerDialog.jsx",
  "src/features/grade-formula/GradeBoundaryBar.jsx",
  "src/features/grade-formula/GradeFormulaPage.jsx",
  "src/features/history/components/HistoryRunRow.jsx",
  "src/features/map/components/MapPage.jsx",
  "src/features/map/viz/components/GalaxyView.jsx",
  "src/features/map/viz/components/PackInfoPanel.jsx",
  "src/features/map/viz/components/ZoomablePackView.jsx",
  "src/features/map/viz/components/galaxyViewDraw.js",
  "src/features/map/viz/components/galaxyViewEvents.js",
  "src/features/map/viz/components/galaxyViewScene.js",
  "src/features/map/viz/components/useGalaxyCamera.js",
  "src/features/onboarding/components/steps/StandardLaunchStep.jsx",
  "src/features/onboarding/hooks/useRepoScanStep.js",
  "src/features/settings/components/CloudProviderTab.jsx",
  "src/features/settings/components/ModelSection.jsx",
  "src/features/settings/components/ServerSection.jsx",
  "src/features/settings/components/SharedRepoSection.jsx",
  "src/features/settings/components/UpdatesSection.jsx",
  "src/features/settings/hooks/useAssistantProvider.js",
  "src/features/settings/llamacpp-log/LlamaCppLogProvider.jsx",
  "src/features/side-pane/SidePane.jsx",
  "src/features/side-pane/SidePaneProvider.jsx",
  "src/features/side-pane/SidePaneWindow.jsx",
  "src/features/standards/components/LibraryBrowser.jsx",
  "src/features/standards/components/RequirementForm.jsx",
  "src/features/standards/components/StandardTree.jsx",
  "src/features/standards/hooks/useStandards.js",
  "src/features/standards/hooks/useVisibleStandards.js",
  "src/features/terminal/TerminalHeader.jsx",
  "src/features/terminal/TerminalPane.jsx",
  "src/features/terminal/TerminalSessionView.jsx",
  "src/features/terminal/useTerminalSessions.js",
  "src/features/terminal/useTerminalSocket.js",
  "src/features/violations/components/DimensionHeatGridView.jsx",
  "src/features/violations/components/useDismissedFindings.js",
  "src/hooks/useAppState.js",
  "src/hooks/useEvaluationLifecycle.js",
  "src/hooks/useNavStack.js",
  "src/hooks/useProjectActions.js",
  "src/hooks/useProjectScores.js",
  "src/hooks/useProjectState.js",
  "src/hooks/useRunNavigator.js",
];
