"""AI provider selection and configuration persistence."""

from __future__ import annotations

import os
import tempfile

from quodeq.config.paths import ConfigPaths
from quodeq.shared.logging import log_error, log_info, log_success, log_warning
from quodeq.shared.utils import get_ai_provider

_AI_PROVIDER_EXPORT_PREFIX = "export AI_PROVIDER="
_OWNER_RW_PERMS = 0o600
_API_KEY_FORBIDDEN_CHARS = ("\n", "\r", "\0")

PROVIDERS = {
    "claude": ("ANTHROPIC_API_KEY", "claude"),
    "codex": ("CODEX_API_KEY", "codex"),
    "gemini": ("GEMINI_API_KEY", "gemini"),
    "ollama": ("", "ollama"),
    "llamacpp": ("", "llamacpp"),
    "openrouter": ("OPENROUTER_API_KEY", "openrouter"),
    "custom": ("AI_API_KEY", "custom"),
}


def get_current_provider(
    paths: ConfigPaths,
    *,
    provider: str | None = None,
    default_provider: str | None = None,
) -> str:
    """Return the currently configured AI provider name, defaulting to 'claude'.

    When *provider* is given it is returned directly, skipping file and env
    lookups.  This makes the function easily testable without env mutation.

    *default_provider* overrides the env-based fallback when no config file
    entry is found, making the function fully testable without env mutation.
    """
    if provider is not None:
        return provider
    if paths.env_file.exists():
        for line in paths.env_file.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith(_AI_PROVIDER_EXPORT_PREFIX):
                return line.split("=", 1)[1].strip()
    if default_provider is not None:
        return default_provider
    return get_ai_provider()


def _write_env(paths: ConfigPaths, provider: str, api_key_var: str, api_key_value: str) -> None:
    lines = [
        "# Quodeq provider config (generated by quodeq configure --ai-cli)",
        f"export AI_PROVIDER={provider}",
    ]
    if api_key_value:
        # Reject control characters that would let a malformed input append
        # extra `export …` lines to the env file.
        if any(ch in api_key_value for ch in _API_KEY_FORBIDDEN_CHARS):
            raise ValueError("API key contains forbidden control characters")
        # SECURITY: The raw API key value is written to the env file in
        # cleartext because it must be sourced by subprocesses at runtime.
        # The file is created with mode 0600 (owner read/write only) via
        # atomic write + fchmod.  This is a known trade-off for local CLI
        # tools where no platform keychain integration is available.
        #
        # For production / shared-server deployments:
        #   - Use the QUODEQ_API_KEY environment variable directly, or
        #   - Store the key in a platform keychain (macOS Keychain,
        #     GNOME Keyring, Windows Credential Manager), or
        #   - Use a secrets manager (Vault, AWS Secrets Manager, etc.)
        lines.append(f"export {api_key_var}={api_key_value}")
        masked = "***" + api_key_value[-4:] if len(api_key_value) > 4 else "****"
        log_warning(
            f"API key ({masked}) will be stored in cleartext at "
            f"{paths.env_file} (mode 0600). For production deployments, "
            f"prefer the QUODEQ_API_KEY environment variable, a platform "
            f"keychain, or a secrets manager instead of writing keys to disk."
        )
    fd, tmp_path = tempfile.mkstemp(dir=str(paths.env_file.parent), suffix=".tmp")
    closed = False
    try:
        os.fchmod(fd, _OWNER_RW_PERMS)
        os.write(fd, ("\n".join(lines) + "\n").encode())
        os.close(fd)
        closed = True
        os.replace(tmp_path, str(paths.env_file))
        os.chmod(str(paths.env_file), _OWNER_RW_PERMS)
    except BaseException:
        if not closed:
            os.close(fd)
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _ensure_gitignore(paths: ConfigPaths) -> None:
    if not paths.gitignore_file.exists():
        return
    content = paths.gitignore_file.read_text(encoding="utf-8").splitlines()
    if ".quodeq.env" not in content:
        content.append(".quodeq.env")
        paths.gitignore_file.write_text("\n".join(content) + "\n", encoding="utf-8")
        log_info("Added .quodeq.env to .gitignore")


def configure_provider_noninteractive(provider: str, paths: ConfigPaths) -> int:
    """Write the chosen AI provider to the env file without interactive prompts."""
    if provider not in PROVIDERS:
        valid = ", ".join(sorted(PROVIDERS.keys()))
        log_error(f"Invalid provider: {provider}. Expected one of: {valid}")
        return 1
    api_key_var, _ = PROVIDERS[provider]
    api_key_value = ""
    _write_env(paths, provider, api_key_var, api_key_value)
    _ensure_gitignore(paths)
    log_success(f"Provider set to '{provider}'. Config saved to .quodeq.env")
    return 0
