from __future__ import annotations

import os

from quodeq.config.paths import ConfigPaths
from quodeq.logging import log_error, log_info, log_success

PROVIDERS = {
    "claude": ("ANTHROPIC_API_KEY", "claude"),
    "copilot": ("GITHUB_TOKEN", "copilot"),
    "codex": ("CODEX_API_KEY", "codex"),
}


def get_current_provider(paths: ConfigPaths) -> str:
    if paths.env_file.exists():
        for line in paths.env_file.read_text().splitlines():
            if line.strip().startswith("export AI_PROVIDER="):
                return line.split("=", 1)[1].strip()
    return os.environ.get("AI_PROVIDER", "claude")


def _write_env(paths: ConfigPaths, provider: str, api_key_var: str, api_key_value: str) -> None:
    lines = [
        "# Quodeq provider config (generated by quodeq configure --ai-cli)",
        f"export AI_PROVIDER={provider}",
    ]
    if api_key_value:
        lines.append(f"export {api_key_var}={api_key_value}")
    paths.env_file.write_text("\n".join(lines) + "\n")


def _ensure_gitignore(paths: ConfigPaths) -> None:
    if not paths.gitignore_file.exists():
        return
    content = paths.gitignore_file.read_text().splitlines()
    if ".quodeq.env" not in content:
        content.append(".quodeq.env")
        paths.gitignore_file.write_text("\n".join(content) + "\n")
        log_info("Added .quodeq.env to .gitignore")


def configure_provider_noninteractive(provider: str, paths: ConfigPaths) -> int:
    if provider not in PROVIDERS:
        log_error(f"Invalid provider: {provider}. Expected: claude, copilot, or codex.")
        return 1
    api_key_var, _ = PROVIDERS[provider]
    api_key_value = ""
    _write_env(paths, provider, api_key_var, api_key_value)
    _ensure_gitignore(paths)
    log_success(f"Provider set to '{provider}'. Config saved to .quodeq.env")
    return 0
