"""AI provider selection and configuration persistence."""

from __future__ import annotations

import os
import re
import tempfile

import keyring

from quodeq.config.paths import ConfigPaths, default_paths
from quodeq.shared.logging import log_debug, log_error, log_info, log_success, log_warning
from quodeq.shared.utils import get_ai_provider

_KEYRING_SERVICE = "quodeq"

_ENV_FILE_HEADER = "# Quodeq provider config (generated by quodeq configure --ai-cli)"
_AI_PROVIDER_EXPORT_PREFIX = "export AI_PROVIDER="
_OWNER_RW_PERMS = 0o600
_API_KEY_FORBIDDEN_CHARS = ("\n", "\r", "\0")
# Provider names reach this module straight from the POST /api/provider/key
# request body and get interpolated into `export …` lines (both as the
# AI_PROVIDER value and, upper-cased, as the key's env var name). A newline
# there injects arbitrary extra env vars, which config/_env_loader.py then
# loads into os.environ. Identifier-shaped names only.
_VALID_PROVIDER_RE = re.compile(r"^[A-Za-z0-9_-]+$")

PROVIDERS = {
    "claude": ("ANTHROPIC_API_KEY", "claude"),
    "codex": ("CODEX_API_KEY", "codex"),
    "gemini": ("GEMINI_API_KEY", "gemini"),
    "ollama": ("", "ollama"),
    "llamacpp": ("", "llamacpp"),
    "openrouter": ("OPENROUTER_API_KEY", "openrouter"),
    "custom": ("AI_API_KEY", "custom"),
}


def get_current_provider(
    paths: ConfigPaths,
    *,
    provider: str | None = None,
    default_provider: str | None = None,
) -> str:
    """Return the currently configured AI provider name, defaulting to 'claude'.

    When *provider* is given it is returned directly, skipping file and env
    lookups.  This makes the function easily testable without env mutation.

    *default_provider* overrides the env-based fallback when no config file
    entry is found, making the function fully testable without env mutation.
    """
    if provider is not None:
        return provider
    if paths.env_file.exists():
        for line in paths.env_file.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith(_AI_PROVIDER_EXPORT_PREFIX):
                return line.split("=", 1)[1].strip()
    if default_provider is not None:
        return default_provider
    return get_ai_provider()


def validate_provider_name(provider: str) -> None:
    """Raise ValueError unless *provider* is safe to write into an env file."""
    if not provider or not _VALID_PROVIDER_RE.match(provider):
        raise ValueError(
            "Provider name must contain only letters, digits, '-' and '_'",
        )


def _existing_env_lines(paths: ConfigPaths) -> list[str]:
    if paths.env_file is None or not paths.env_file.exists():
        return []
    try:
        return paths.env_file.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []


def _validate_env_write(provider: str | None, api_key_var: str, api_key_value: str) -> None:
    """Reject anything that would inject extra lines or write a malformed one."""
    if api_key_value:
        # Reject control characters that would let a malformed input append
        # extra `export …` lines to the env file.
        if any(ch in api_key_value for ch in _API_KEY_FORBIDDEN_CHARS):
            raise ValueError("API key contains forbidden control characters")
        if not api_key_var or not _VALID_PROVIDER_RE.match(api_key_var):
            # PROVIDERS maps keyless providers (ollama, llamacpp) to "",
            # which would otherwise produce a malformed `export =<key>` line.
            raise ValueError("Provider has no API key environment variable")
    if provider is not None:
        validate_provider_name(provider)


def _preserved_env_lines(
    paths: ConfigPaths, provider: str | None, replaced_key_prefix: str | None,
) -> tuple[str | None, list[str]]:
    """Return (AI_PROVIDER line, everything else) from the current env file.

    Rebuilding the file from a fixed template used to wipe every other
    provider's stored key, and a key save used to silently switch
    AI_PROVIDER. Everything already on disk survives except the two lines
    the caller actually owns: the AI_PROVIDER line (only when *provider* is
    not None -- a key save passes None so it never changes the active
    provider) and the ``export {api_key_var}=`` line being replaced.
    """
    replaced = []
    if provider is not None:
        replaced.append(_AI_PROVIDER_EXPORT_PREFIX)
    if replaced_key_prefix:
        replaced.append(replaced_key_prefix)

    provider_line = f"export AI_PROVIDER={provider}" if provider is not None else None
    body: list[str] = []
    for raw in _existing_env_lines(paths):
        stripped = raw.strip()
        if not stripped or stripped == _ENV_FILE_HEADER:
            continue
        if any(stripped.startswith(prefix) for prefix in replaced):
            continue
        if stripped.startswith(_AI_PROVIDER_EXPORT_PREFIX):
            # Preserved verbatim, re-emitted right after the header.
            provider_line = raw
            continue
        body.append(raw)
    return provider_line, body


def _build_env_lines(
    paths: ConfigPaths, provider: str | None, api_key_var: str, api_key_value: str,
) -> list[str]:
    """Merge the requested change into the existing ``.quodeq.env`` content."""
    _validate_env_write(provider, api_key_var, api_key_value)
    provider_line, body = _preserved_env_lines(
        paths, provider, f"export {api_key_var}=" if api_key_value else None,
    )
    lines = [_ENV_FILE_HEADER]
    if provider_line:
        lines.append(provider_line)
    lines.extend(body)
    if not api_key_value:
        return lines
    # SECURITY: The raw API key value is written to the env file in
    # cleartext because it must be sourced by subprocesses at runtime.
    # The file is created with mode 0600 (owner read/write only) via
    # atomic write + fchmod.  This is a known trade-off for local CLI
    # tools where no platform keychain integration is available.
    #
    # For production / shared-server deployments:
    #   - Use the QUODEQ_API_KEY environment variable directly, or
    #   - Store the key in a platform keychain (macOS Keychain,
    #     GNOME Keyring, Windows Credential Manager), or
    #   - Use a secrets manager (Vault, AWS Secrets Manager, etc.)
    lines.append(f"export {api_key_var}={api_key_value}")
    masked = "***" + api_key_value[-4:] if len(api_key_value) > 4 else "****"
    log_warning(
        f"API key ({masked}) will be stored in cleartext at "
        f"{paths.env_file} (mode 0600). For production deployments, "
        f"prefer the QUODEQ_API_KEY environment variable, a platform "
        f"keychain, or a secrets manager instead of writing keys to disk."
    )
    return lines


def _write_env(
    paths: ConfigPaths, provider: str | None, api_key_var: str, api_key_value: str,
) -> None:
    lines = _build_env_lines(paths, provider, api_key_var, api_key_value)
    fd, tmp_path = tempfile.mkstemp(dir=str(paths.env_file.parent), suffix=".tmp")
    closed = False
    try:
        # os.fchmod is POSIX-only; on Windows it is absent. The
        # post-replace os.chmod below carries the 0600 guarantee on POSIX,
        # and mkstemp already creates the temp file 0600, so skipping
        # fchmod on Windows loses no hardening.
        if hasattr(os, "fchmod"):
            os.fchmod(fd, _OWNER_RW_PERMS)
        os.write(fd, ("\n".join(lines) + "\n").encode())
        os.close(fd)
        closed = True
        os.replace(tmp_path, str(paths.env_file))
        os.chmod(str(paths.env_file), _OWNER_RW_PERMS)
    except BaseException:
        if not closed:
            os.close(fd)
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def _ensure_gitignore(paths: ConfigPaths) -> None:
    if not paths.gitignore_file.exists():
        return
    content = paths.gitignore_file.read_text(encoding="utf-8").splitlines()
    if ".quodeq.env" not in content:
        content.append(".quodeq.env")
        paths.gitignore_file.write_text("\n".join(content) + "\n", encoding="utf-8")
        log_info("Added .quodeq.env to .gitignore")


def configure_provider_noninteractive(provider: str, paths: ConfigPaths) -> int:
    """Write the chosen AI provider to the env file without interactive prompts."""
    if provider not in PROVIDERS:
        valid = ", ".join(sorted(PROVIDERS.keys()))
        log_error(f"Invalid provider: {provider}. Expected one of: {valid}")
        return 1
    api_key_var, _ = PROVIDERS[provider]
    api_key_value = ""
    _write_env(paths, provider, api_key_var, api_key_value)
    _ensure_gitignore(paths)
    log_success(f"Provider set to '{provider}'. Config saved to .quodeq.env")
    return 0


def _api_key_var_for(provider: str) -> str:
    """Return the env var name used to persist *provider*'s key in cleartext."""
    api_key_var, _ = PROVIDERS.get(provider, (f"{provider.upper()}_API_KEY", provider))
    return api_key_var


def _store_api_key(provider: str, api_key: str) -> tuple[bool, bool]:
    """Store *provider*'s key and report how. Returns (stored, secure).

    Raises ValueError for a provider name that is not identifier-shaped.
    Checked here, before either backend, so the keyring and the cleartext
    paths are both covered by one guard.
    """
    validate_provider_name(provider)
    try:
        keyring.set_password(_KEYRING_SERVICE, provider, api_key)
        return True, True
    except Exception as exc:  # keyring.errors.KeyringError, or an unconfigured backend raising something else
        log_debug(f"keyring unavailable for '{provider}', falling back to cleartext: {exc}")

    paths = default_paths()
    try:
        # provider=None: saving a key must never silently switch the active
        # provider. Only configure_provider_noninteractive sets AI_PROVIDER.
        _write_env(paths, None, _api_key_var_for(provider), api_key)
        _ensure_gitignore(paths)
        return True, False
    except Exception as exc:
        log_error(f"Failed to store API key for '{provider}': {exc}")
        return False, False


def store_api_key_secure(provider: str, api_key: str) -> bool:
    """Persist *provider*'s API key, preferring the OS keyring over cleartext.

    Tries the platform keyring first; on failure falls back to the existing
    cleartext `.quodeq.env` write path. Returns True if either succeeded.
    """
    stored, _secure = _store_api_key(provider, api_key)
    return stored


def get_api_key_secure(provider: str) -> str | None:
    """Return *provider*'s stored API key, checking the keyring then the
    cleartext `.quodeq.env` fallback. None if stored nowhere."""
    try:
        value = keyring.get_password(_KEYRING_SERVICE, provider)
        if value:
            return value
    except Exception as exc:
        log_debug(f"keyring lookup failed for '{provider}': {exc}")

    paths = default_paths()
    if paths.env_file is None or not paths.env_file.exists():
        return None
    api_key_var = _api_key_var_for(provider)
    if not api_key_var:
        return None
    prefix = f"export {api_key_var}="
    for line in paths.env_file.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith(prefix):
            return line.split("=", 1)[1].strip()
    return None
