"""Re-export for backward compatibility — moved to quodeq.analysis.subprocess."""
from quodeq.analysis.subprocess import (  # noqa: F401
    HeartbeatCallback,
    AnalysisConfig,
    AnalysisError,
    count_files_from_stream,
    run_analysis,
    _IncrementalProgressReader,
    _create_mcp_config,
    _get_ai_tools,
    _get_base_ai_args,
    _load_provider_configs,
    _build_ai_cmd,
    _terminate_process,
    _run_with_heartbeat,
    _build_analysis_env,
    _check_process_result,
    _spawn_and_monitor,
    _sanitize_stderr,
)
